[build]
  base = "AHH" # Only include this line if AHH is a directory containing your project files.
  publish = "AHH/public" # Adjust to the directory where your build output is located.
  command = "node index.js" # Replace with your actual build command, or remove if not needed.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200