[build]
  base = "AHH" # Only if your project is in a subfolder named AHH
  publish = "AHH/public" # Adjust to your actual publish directory
  # command = "npm run build" # Uncomment and adjust if you have a build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200