[build]
  # base = "AHH" # Comment this out if your project root is the repository root
  publish = "public" # Adjust if your static site files are in a different directory
  command = "nodemon index.js" # Your actual start command

[functions]
  directory = "netlify/functions" # Adjust if necessary, and ensure the directory exists

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
