[build]
  base = "AHH"
  publish = "AHH/public" # Adjust this path to where your static site files are generated
  command = "npm run build" # Adjust this command to your actual build command

[functions]
  directory = "AHH/netlify/functions" # Assuming your functions are in this directory, adjust if necessary

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
